name: E2e testing

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  cypress:
    defaults:
      run:
        working-directory: dashboard

    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
        env:
          NODE_ENV: production
          VUE_APP_API_BASE_URL: https://feedbacker-api.matheusmf.dev

      - name: Run project locally
        run: |
          yarn add serve
          $(yarn bin)/serve dist -s -p 8080 &

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: dashboard
          browser: chrome
          headless: true
